#!/usr/bin/env bash
#
# This script is used to clear the setup generated by clarity5gC.sh
#
# Author: Daniel Camps (daniel.camps@i2cat.net)
# Copyright: i2CAT


#############################
# Parsing inputs parameters
#############################

usage() { echo "Usage: $0 [-n <NUM_UEs>]" 1>&2; exit 1; }

while getopts ":n:" o; do
    case "${o}" in
        n)
            NUM_UES=${OPTARG}
            n=1
            echo "NUM_UEs="$NUM_UES
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${n}" ]; then
    usage
fi

##############################
# Environment configuration
##############################

# Check OS
if [ -f /etc/os-release ]; then
    # freedesktop.org and systemd
    . /etc/os-release
    OS=$NAME
    VER=$VERSION_ID
else
    # Fall back to uname, e.g. "Linux <version>", also works for BSD, etc.
    OS=$(uname -s)
    VER=$(uname -r)
    echo "This Linux version is too old: $OS:$VER, we don't support!"
    exit 1
fi

sudo -v
if [ $? == 1 ]
then
    echo "Without root permission, you cannot run the test due to our test is using namespace"
    exit 1
fi

GOPATH=$HOME/go
if [ $OS == "Ubuntu" ]; then
    GOROOT=/usr/local/go
elif [ $OS == "Fedora" ]; then
    GOROOT=/usr/lib/golang
fi
PATH=$PATH:$GOPATH/bin:$GOROOT/bin


###########################
# Deleting UPF namespace
##########################

UPFNS="UPFns"
EXEC_UPFNS="sudo ip netns exec ${UPFNS}"

sleep 1
sudo killall -15 free5gc-upfd
sleep 1

sudo ip link del veth0
sudo ip netns del ${UPFNS}
sudo ip addr del 60.60.0.1/32 dev lo

BRNAME="br_dn"
VETH_DN="veth_dn_h"

sudo ip xfrm policy flush
sudo ip xfrm state flush
sudo ip link del $VETH_DN
sudo ip link del ipsec0
sudo ifconfig $BRNAME down
sudo brctl delbr $BRNAME

# Restoring ip address for eth2
sudo ifconfig "eth2" "192.168.20.2/24" up

###########################
# Deleting N3IWF
##########################

sudo killall n3iwf
killall test.test
cp -f config/amfcfg.conf.bak config/amfcfg.conf
rm -f config/amfcfg.conf.bak
